language: java
jdk: oraclejdk8
script:
  - export _JAVA_OPTIONS="-Xms2048m -Xmx4096m"
  - ./gradlew clean build
notifications:
  email:
    recipients:
      - kh.mv@bk.ru
    on_success: never
    on_failure: always